AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - spec/dummy/db/schema.rb
    - spec/dummy/db/migrate/20200628202101_create_active_storage_tables.active_storage.rb

Metrics/BlockLength:
  Exclude:
    - spec/dummy/config/environments/development.rb

Style/Documentation:
  Enabled: false
